export interface Property {
  id: string
  title: string
  price: number
  address: string
  city: string
  type: "Apartment" | "House" | "Land" | "Commercial"
  listingType: "sale" | "rent"
  bedrooms: number
  bathrooms: number
  size: number
  image: string
  description: string
  amenities: string[]
  lat: number
  lng: number
  agent?: string
  agency?: string
  badge?: "NEW" | "URGENT" | "TOP" | null
  yearBuilt?: number
  floor?: number
}

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    price: 250000,
    address: "123 Main Street",
    city: "Bucharest",
    type: "Apartment",
    listingType: "sale",
    bedrooms: 2,
    bathrooms: 2,
    size: 85,
    image: "/modern-apartment.png",
    description: "Beautiful modern apartment in the heart of downtown with stunning city views.",
    amenities: ["balcony", "parking", "furnished"],
    lat: 44.4268,
    lng: 26.1025,
    agent: "Maria Popescu",
    agency: "Prime Real Estate",
    badge: "NEW",
    yearBuilt: 2022,
    floor: 5,
  },
  {
    id: "2",
    title: "Luxury Villa with Pool",
    price: 850000,
    address: "456 Oak Avenue",
    city: "Cluj-Napoca",
    type: "House",
    listingType: "sale",
    bedrooms: 5,
    bathrooms: 4,
    size: 320,
    image: "/luxury-villa-pool.png",
    description: "Stunning luxury villa with private pool and garden in exclusive neighborhood.",
    amenities: ["balcony", "parking", "garden", "pool"],
    lat: 46.7712,
    lng: 23.6236,
    agent: "Ion Ionescu",
    agency: "Luxury Homes",
    badge: "TOP",
    yearBuilt: 2021,
  },
  {
    id: "3",
    title: "Cozy Studio Near University",
    price: 800,
    address: "789 Student Street",
    city: "Bucharest",
    type: "Apartment",
    listingType: "rent",
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    image: "/cozy-studio-apartment.png",
    description: "Perfect studio for students, fully furnished and close to public transport.",
    amenities: ["furnished", "parking"],
    lat: 44.4378,
    lng: 26.0495,
    agent: "Ana Dumitrescu",
    agency: "Student Housing",
    badge: "URGENT",
    yearBuilt: 2018,
    floor: 3,
  },
  {
    id: "4",
    title: "Commercial Space Downtown",
    price: 3500,
    address: "321 Business Boulevard",
    city: "Timișoara",
    type: "Commercial",
    listingType: "rent",
    bedrooms: 0,
    bathrooms: 2,
    size: 150,
    image: "/modern-commercial-office-space.jpg",
    description: "Prime commercial space in busy downtown area, perfect for retail or office.",
    amenities: ["parking", "elevator"],
    lat: 45.7489,
    lng: 21.2087,
    agent: "Mihai Georgescu",
    agency: "Commercial Properties",
    badge: null,
    yearBuilt: 2019,
    floor: 1,
  },
  {
    id: "5",
    title: "Building Plot with Views",
    price: 120000,
    address: "Hill Road 55",
    city: "Brașov",
    type: "Land",
    listingType: "sale",
    bedrooms: 0,
    bathrooms: 0,
    size: 1200,
    image: "/land-plot-mountain-views.jpg",
    description: "Excellent building plot with panoramic mountain views and all utilities.",
    amenities: [],
    lat: 45.6427,
    lng: 25.5887,
    agent: "Elena Radu",
    agency: "Land Investments",
    badge: "NEW",
  },
  {
    id: "6",
    title: "Penthouse with Terrace",
    price: 450000,
    address: "88 Skyline Tower",
    city: "Bucharest",
    type: "Apartment",
    listingType: "sale",
    bedrooms: 3,
    bathrooms: 3,
    size: 180,
    image: "/luxury-penthouse-terrace.png",
    description: "Exclusive penthouse with large terrace and 360-degree city views.",
    amenities: ["balcony", "parking", "furnished", "elevator"],
    lat: 44.4479,
    lng: 26.0979,
    agent: "Cristian Popa",
    agency: "Elite Properties",
    badge: "TOP",
    yearBuilt: 2023,
    floor: 12,
  },
  {
    id: "7",
    title: "Family House with Garden",
    price: 1500,
    address: "12 Green Lane",
    city: "Sibiu",
    type: "House",
    listingType: "rent",
    bedrooms: 4,
    bathrooms: 2,
    size: 200,
    image: "/family-house-garden.png",
    description: "Spacious family home with beautiful garden in quiet residential area.",
    amenities: ["garden", "parking", "furnished"],
    lat: 45.7983,
    lng: 24.1256,
    agent: "Andreea Stan",
    agency: "Family Homes",
    badge: null,
    yearBuilt: 2015,
  },
  {
    id: "8",
    title: "Modern Loft Space",
    price: 1200,
    address: "99 Industrial Street",
    city: "Cluj-Napoca",
    type: "Apartment",
    listingType: "rent",
    bedrooms: 2,
    bathrooms: 1,
    size: 95,
    image: "/modern-industrial-loft.jpg",
    description: "Trendy loft apartment in converted industrial building with high ceilings.",
    amenities: ["balcony", "furnished", "elevator"],
    lat: 46.7667,
    lng: 23.5833,
    agent: "Vlad Marin",
    agency: "Urban Living",
    badge: "NEW",
    yearBuilt: 2020,
    floor: 2,
  },
]
